language: node_js

node_js: "4.4.5"

os:
  - osx

before_install:
  - brew cask install virtualbox
  - brew install docker docker-machine
  - docker-machine create main
  - "npm install"

script:
  - "node builder.js"

