language: node_js

node_js: "4.4.5"

os:
  - linux
  - osx
  
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:snappy-dev/tools-proposed -y

  - sudo apt-get update

  - sudo apt-get install snapcraft -y
  
  - "npm install"

script:
  - "node builder.js"

