language: node_js

node_js: "4.4.5"

os: linux
dist: trusty
sudo: required
language: generic

services:
- docker

env:
  global:
  - DOCKER_IMAGE=ubuntu:xenial

before_install:
  - ./travis-build.sh before_install
  
install:
  - ./travis-build.sh install

script:
  - ./travis-build.sh script
