language: node_js

node_js: "4.4.5"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - ./linux-setup.sh
  - "npm install"

script:
  - "node builder.js"
