language: node_js

node_js: "6.11"

os:
    - linux
    - osx
    
dist: trusty
sudo: required

osx_image: xcode7.3

cache:
  directories:
    - "node_modules"

services:
    - docker

env:
  global:
    - ANDROID_HOME=/usr/local/opt/android-sdk
    - WINEDLLOVERRIDES="mshtml="
    - secure: hhh+idGdiVlW9TXywJIO840U3RR+Rd3WyzMpfDF98NnGjuq9BF8+0+dP1JxictffjmYWndiJ+lh6sMgScyGMzwRqkbovedBMFCqDBAYJBSIo+8HUKk50X75fr1uFt4bX20c6OguZyBP8NoZMWWxkfXF82vM4JFPQl3kVhoFkeU0=
    - DOCKER_IMAGE=ubuntu:xenial
  matrix:
    - BUILD_TARGET=browser
    - BUILD_TARGET=everything
    - BUILD_TARGET=snap
    
matrix:
  exclude:
  - os: osx
    env: BUILD_TARGET=snap
  - os: linux
    env: BUILD_TARGET=browser
  - os: linux
    env: BUILD_TARGET=everything

before_install:

  # Install node build tools
  - npm install -g gulp
  
deploy:
 # Trunk
  - provider: s3
    access_key_id: "MYKEYISSHIT"
    secret_access_key: "MYSECRETISNOTASECRET"
    region: "BRAZIL"
    skip_cleanup: true
    local_dir: travis/s3-upload-index
    upload-dir: test/aa
    detect_encoding: true
    cache_control: "no-cache"
    bucket: "test"
    on:
      condition: "BUILD_TARGET = browser"
