language: node_js

node_js: "4.4.5"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install snapcraft; fi
  - "npm install"

script:
  - "node builder.js"

