language: node_js

node_js: "4.4.5"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=ubuntu:xenial

before_install:
 - chmod +x travis-setup.sh
 - chmod +x travis-linux-setup.sh
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-setup.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-setup.sh before_install; fi
  
  - "npm install -g gulp"

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-setup.sh install; fi

script:
  - "gulp travis-package"

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-setup.sh script; fi
