language: node_js

node_js: "6.11"

os:
    - linux
    - osx
    
dist: trusty
sudo: required

osx_image: xcode7.3

cache:
  directories:
    - "node_modules"

services:
    - docker

env:
  global:
    - ANDROID_HOME=/usr/local/opt/android-sdk
    - WINEDLLOVERRIDES="mshtml="
    - secure: hhh+idGdiVlW9TXywJIO840U3RR+Rd3WyzMpfDF98NnGjuq9BF8+0+dP1JxictffjmYWndiJ+lh6sMgScyGMzwRqkbovedBMFCqDBAYJBSIo+8HUKk50X75fr1uFt4bX20c6OguZyBP8NoZMWWxkfXF82vM4JFPQl3kVhoFkeU0=
    - DOCKER_IMAGE=ubuntu:xenial
  matrix:
    - BUILD_TARGET=browser
    - BUILD_TARGET=everything
    - BUILD_TARGET=snap
      

before_install:
  - chmod +x travis-linux-setup.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-setup.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-setup.sh; fi

  # Install node build tools
  - npm install -g gulp

script:
  - "travis_wait 90 gulp travis-package --build $BUILD_TARGET"
