language: node_js

node_js: "4.4.5"

os: osx
osx_image: xcode7.3

before_install:
  - docker run --rm -ti -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:latest
  - "npm install"

script:
  - "node builder.js"

