language: node_js

node_js: "4.4.5"

os:
  - osx

before_install:
  - brew cask install virtualbox
  - brew install docker docker-machine
  - docker-machine create --vmwarefusion-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/download/v1.3.2/boot2docker.iso --driver vmwarefusion main
  - "npm install"

script:
  - "node builder.js"

