language: node_js

node_js: "4.4.5"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - sudo add-apt-repository ppa:snappy-dev/tools
  - sudo apt-get -qq update
  - sudo apt-get install -y snapcraft
  - "npm install"

script:
  - "node builder.js"

