name: electron-sample
version: 1.0.0
summary: electron-sample
vendor: denner_erthal@hotmail.com
description: electron-sample
confinement: strict
icon: gui/icon.png
grade: stable
apps:
  electron-sample:
    command: desktop-launch $SNAP/electron-sample
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: /linux-unpacked
    after:
      - desktop-qt5
